
version: 2

sources:
  - name: SNOWFLAKE_STORE_SALES
    description: "snowflake sample store sales data."
    database: "SNOWFLAKE_SAMPLE_DATA"
    schema: "TPCDS_SF100TCL"
    tables: 
      - name: "STORE_SALES"
